SELECT CONCAT(
	'ALTER TABLE '
	, TABLE_NAME
	, ' ADD '
	, COLUMN_NAME
	, ' '
	, DATA_TYPE
	, CASE WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL THEN CONCAT('(', CHARACTER_MAXIMUM_LENGTH, ')') END
	, ' '
	, CASE WHEN IS_NULLABLE = 'YES' THEN 'NULL' ELSE 'NOT NULL' END
) AS column_definition, *
FROM INFORMATION_SCHEMA.COLUMNS